name: Generate Snake

on:
  # Har raat 12 baje automatically run hoga
  schedule:
    - cron: "0 0 * * *" 
  
  # Aap manually bhi run kar sakte hain
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v3
        with:
          # Aapka GitHub Username
          github_user_name: Ritik-2901
          outputs: dist/github-contribution-grid-snake.svg
      
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
